[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
blitz_games = "9DK1L9UF4EmkrMPpv9FZs4B63RvVPwJR34NGWm9NEbVy"

[programs.mainnet]
blitz_games = "9DK1L9UF4EmkrMPpv9FZs4B63RvVPwJR34NGWm9NEbVy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/prada/mainnet-deployer-v2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
